# **WINE QUALITY PREDICTION USING SUPPORT VECTOR MACHINE**

# Get Understanding about Data set

White wine data has twelve variables
1. Fixed acidity
2. volatine acidity
3. citric acid
4. residual sugar 
5. chlorides
6. free sulfur dioxide
7. total sulfur dioxide
8. density
9. pH
10. suphalte
11. alcohol
12. quality

# Import Library

In [3]:
import numpy as np
import pandas as pd

# Cleaning the dataset

In [4]:
wine= pd.read_csv(r'https://github.com/YBIFoundation/Dataset/raw/main/WhiteWineQuality.csv',sep=';')
wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

# Get the First Five Rows of Dataframe

In [5]:
wine.columns=['fixed acidity' ,'volatile acidity','citric acid','residual sugar' ,'chlorides' ,'free sulfur dioxide', 'total sulfur dioxide','density', 'pH','sulphates','alcohol','quality']
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

# Get information of Dataframe

In [6]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 459.3 KB


# Get the summary Statistics

In [7]:
wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

# Get column Names

In [8]:
wine.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

# Get Shape of the dataframe

In [9]:
wine.shape

(4898, 12)

In [10]:
wine.shape

(4898, 12)

# Get unique values (Class or Label) in y Variable

In [11]:
wine['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [12]:
wine.groupby('quality').mean()

fixed acidity  volatile acidity  citric acid  residual sugar  \
quality                                                                 
3             7.600000          0.333250     0.336000        6.392500   
4             7.129448          0.381227     0.304233        4.628221   
5             6.933974          0.302011     0.337653        7.334969   
6             6.837671          0.260564     0.338025        6.441606   
7             6.734716          0.262767     0.325625        5.186477   
8             6.657143          0.277400     0.326514        5.671429   
9             7.420000          0.298000     0.386000        4.120000   

         chlorides  free sulfur dioxide  total sulfur dioxide   density  \
quality                                                                   
3         0.054300            53.325000            170.600000  0.994884   
4         0.050098            23.358896            125.279141  0.994277   
5         0.051546            36.432052            150.904598  0.995263   
6         0.045217            35.650591            137.047316  0.993961   
7         0.038191            34.125568            125.114773  0.992452   
8         0.038314            36.720000            126.165714  0.992236   
9         0.027400            33.400000            116.000000  0.991460   

               pH  sulphates    alcohol  
quality                                  
3        3.187500   0.474500  10.345000  
4        3.182883   0.476135  10.152454  
5        3.168833   0.482203   9.808840  
6        3.188599   0.491106  10.575372  
7        3.213898   0.503102  11.367936  
8        3.218686   0.486229  11.636000  
9        3.308000   0.466000  12.180000

# define y and x

In [13]:
y=wine['quality']

In [14]:
y.shape

(4898,)

In [15]:
y

0       6
1       6
2       6
3       6
4       6
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 4898, dtype: int64

In [16]:
x= wine.drop(['quality'],axis=1)
y=wine.quality

In [17]:
x.shape

(4898, 11)

In [18]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[4898 rows x 11 columns]

In [19]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  
0      8.8  
1      9.5  
2     10.1  
3      9.9  
4      9.9

In [20]:
y.head()

0    6
1    6
2    6
3    6
4    6
Name: quality, dtype: int64

# Get Train Test Split

In [21]:
# Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2529)

In [22]:
x_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
116             6.0              0.31         0.24             3.3      0.041   
2423            7.2              0.24         0.29             3.0      0.036   
4065            6.6              0.50         0.26            11.3      0.029   
4893            6.2              0.21         0.29             1.6      0.039   
4292            6.9              0.22         0.32             5.8      0.041   
...             ...               ...          ...             ...        ...   
4590            6.4              0.33         0.30             7.2      0.041   
4476            6.0              0.20         0.38             1.3      0.034   
3656            7.1              0.28         0.28             8.5      0.030   
4836            6.7              0.50         0.36            11.5      0.096   
2876            6.4              0.22         0.31            13.9      0.040   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
116                  25.0                 143.0  0.99140  3.31       0.44   
2423                 17.0                 117.0  0.99411  3.36       0.68   
4065                 32.0                 110.0  0.99302  3.27       0.78   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4292                 20.0                 119.0  0.99296  3.17       0.55   
...                   ...                   ...      ...   ...        ...   
4590                 42.0                 168.0  0.99331  3.22       0.49   
4476                 37.0                 104.0  0.98865  3.11       0.52   
3656                 25.0                 191.0  0.99338  3.16       0.46   
4836                 18.0                  92.0  0.99642  3.11       0.49   
2876                 57.0                 135.0  0.99672  3.21       0.38   

      alcohol  
116      11.3  
2423     10.1  
4065     12.9  
4893     11.2  
4292     11.2  
...       ...  
4590     11.1  
4476     12.7  
3656     12.2  
4836      9.6  
2876     10.7  

[3428 rows x 11 columns]

In [23]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3428, 11)
(3428,)
(1470, 11)
(1470,)


# get x variables Standardized

In [24]:
# Standard scaler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [25]:
x_train

array([[-1.02440054,  0.3302746 , -0.78598307, ...,  0.8320846 ,
        -0.42272081,  0.63842357],
       [ 0.41004616, -0.36860276, -0.37020115, ...,  1.16533841,
         1.67943626, -0.33200385],
       [-0.30717719,  2.22722743, -0.6196703 , ...,  0.56548155,
         2.55533504,  1.93232679],
       ...,
       [ 0.29050893,  0.03075573, -0.45335754, ..., -0.16767683,
        -0.24754106,  1.36624413],
       [-0.18763997,  2.22722743,  0.21189353, ..., -0.50093064,
         0.01522858, -0.7363486 ],
       [-0.54625164, -0.56828201, -0.20388839, ...,  0.16557698,
        -0.94826008,  0.15320986]])

# Get model train

In [26]:
from sklearn.svm import SVC

In [27]:
svc=SVC()

In [28]:
svc.fit(x_train,y_train)

SVC()

# Get model Prediction

In [29]:
y_pred=svc.predict(x_test)

In [30]:
y_pred.shape

(1470,)

In [31]:
y_pred

array([6, 5, 6, ..., 6, 5, 6], dtype=int64)

# model evaluation

In [32]:
from sklearn.metrics import confusion_matrix,classification_report

In [33]:
print(confusion_matrix(y_test,y_pred))

[[  0   0   2   2   0   0]
 [  0   1  37  18   1   0]
 [  0   0 248 173   4   0]
 [  0   0 130 503  46   0]
 [  0   0   7 176  74   0]
 [  0   0   1  33  14   0]]


In [34]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       1.00      0.02      0.03        57
           5       0.58      0.58      0.58       425
           6       0.56      0.74      0.64       679
           7       0.53      0.29      0.37       257
           8       0.00      0.00      0.00        48

    accuracy                           0.56      1470
   macro avg       0.45      0.27      0.27      1470
weighted avg       0.56      0.56      0.53      1470



C:\Users\yashm\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\yashm\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\yashm\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

# Get model Re-run with Two classes created for wine quality

In [35]:
# Wine quality 3,4,5 labelled as 0
# wine quality 6,7,8,9 labelled as 1


In [36]:
y=wine['quality'].apply(lambda y_values:1 if y_values>=6 else 0)

In [37]:
y.value_counts()

quality
1    3258
0    1640
Name: count, dtype: int64

# get train test split  


In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2529)

In [39]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3428, 11)
(3428,)
(1470, 11)
(1470,)


# Get model train

In [40]:
from sklearn.svm import SVC

In [41]:
svc=SVC()

In [42]:
svc.fit(x_train,y_train)

SVC()

# Get model prediction

In [43]:
y_pred=svc.predict(x_test)

In [44]:
y_pred.shape

(1470,)

In [45]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

# Get model evaluation

In [46]:
from sklearn.metrics import confusion_matrix,classification_report

In [47]:
print(confusion_matrix(y_test,y_pred))

[[ 13 473]
 [ 12 972]]


In [48]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.52      0.03      0.05       486
           1       0.67      0.99      0.80       984

    accuracy                           0.67      1470
   macro avg       0.60      0.51      0.43      1470
weighted avg       0.62      0.67      0.55      1470



# Get future predictions

**Lets select a random sample from existing dataset as new value**

Steps to follow:
1. Extract a random row using function
2. Seperate X and Y
3. Standardize X
4. Predict

In [49]:
wine_new=wine.sample(1)

In [50]:
wine_new

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3439            6.7               0.4         0.22             8.8      0.052   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
3439                 24.0                 113.0  0.99576  3.22       0.45   

      alcohol  quality  
3439      9.4        5

In [51]:
wine_new.shape

(1, 12)

In [52]:
X_new=wine_new.drop(['quality'],axis=1)

In [53]:
X_new=ss.fit_transform(X_new)

NameError: name 'ss' is not defined

In [54]:
y_pred_new=svc.predict(X_new)

In [55]:
y_pred_new

array([1], dtype=int64)